version: '2.4'

services:
  database:
    image: postgres:14.10-alpine
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 5

  test:
    image: golang:1.22
    links:
      - database
    volumes:
      - ".:/src"
      - "~/.docker-go-cache/mod:/go/pkg/mod"
      - "~/.docker-go-cache/build:/root/.cache/go-build"
    environment:
      TEST_DB: "postgres://test:test@database/test?sslmode=disable"
      INITIAL_ADMIN_USER: "test@example.com:verysecret"
    working_dir: "/src"
    command: "go test ./... -v"
